# The main pipeline for UBC Sailbot projects

pool:
  vmImage: 'Ubuntu 16.04'

steps:
- script: |
    sudo ./install_deps/install_deps_linux.sh
  displayName: 'Install deps'

- task: CMake@1
  displayName: Generate Build Files
  inputs:
    workingDirectory: build
    cmakeArgs: '../'

- script: |
    cd build
    make
  displayName: 'make'
  
- script: |
    cd build
    bin/run_basic_tests --gtest_output=xml
